### ISSUE TITLE
Okay to make this part of the official package?

### ISSUE THREAD

**Issue by sah** [clach04/passogva#1]
I'm the original author of passogva. I came across your changes recently and I'd like to incorporate them. I've forked your repo to create a primary repo I can maintain, and merged your changes there (see https://github.com/sah/passogva/pull/1). 

I'm thinking I'll do a 1.1 release including your changes, and clarify that the license is MIT. Okay with you?

**Comment by clach04** [comment]
👍  @sah, that would be awesome! Thank you for creating this in the first place :)

I'm happy for you to take any changes you want, MIT license sounds good to me.

I'm about to update the readme with a link to your repo :-)
